version: '3'

services:
  #MySQL
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123 # root密码(修改要同时修改data/mysql/init/init.sql中的密码)
      MYSQL_DATABASE: gae
    restart: on-failure
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1
  api:
    container_name: api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /
    environment:
      TZ: Asia/Shanghai
    volumes:
      # 挂载文件
      - ./file:/file

    ports:
      # 映射端口
      - "9000:9000"
    depends_on:
      - mysql

